imalatlar/apps/home/urls.py
from django.urls import path

from .views import *

app_name = "home"

urlpatterns = [
    path('', home_view, name='home'),
    path('kapilar/',kapilar_view,name='kapilar'),
    path('about_sld/', aboutsld_view, name='aboutsld'),
    path('about_mr30/', aboutmr30_view, name='aboutmr30'),
    path('401/', view_401,name='401'),
]

imalatlar/apps/mr30/urls.py
from django.urls import path
from .views import detail_view, create_view, list_view, send_mail

app_name = 'mr30'
urlpatterns = [
    path('goruntule/<id>', detail_view, name='detail'),
    path('olustur', create_view, name='create'),
    path('liste', list_view, name='list'),
    path('gonder/<id>', send_mail, name='send_mail')
]

imalatlar/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("imalatlar.apps.home.urls", namespace='home')),
    path('sld/', include("imalatlar.apps.sld.urls", namespace='sld')),
    path('mr30/', include("imalatlar.apps.mr30.urls", namespace='mr30')),
    path('user/', include("imalatlar.apps.user.urls", namespace='user')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

imalatlar/apps/mr30/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse

from ...common.models import WorkOrderAbstractModel

# WING_DATA = ((3, 3), (4, 4),)
MR30_TYPE_DATA = (
    ('uk_otomatik', 'OTOMATİK 3 KANATLI'),
    ('dk_otomatik', 'OTOMATİK 4 KANATLI'),
    ('uk_manuel', 'MANUEL 3 KANATLI'),
    ('dk_manuel', 'MANUEL 4 KANATLI'),
)

# Burdaki isimlendirmeler js tarafında da aynı şekilde olmalıdır!
# Herhanbi bi değişiklikte dikkatli olunmalı

OPTIONS_LIST = (
    ('HMI El Terminali', 'HMI El Terminali'),
    ('Acil Stop', 'Acil Stop'),
    ('Kart Okuyucu', 'Kart Okuyucu'),
    ('Batarya', 'Batarya'),
)
RADAR_ACTIVATION_LIST = (
    ('Mikrodalga Radar', 'Mikrodalga Radar'),
    ('CombineRadar Safety - Activation', 'CombineRadar Safety - Activation'),
    ('Yaklaşım Sensoru', 'Yaklaşım Sensoru'),
)

GLASS_TYPES = (
    ('4+4 Bombeli Seffaf Lamine', '4+4 Bombeli Seffaf Lamine'),
    ('5+5 Bombeli Seffaf Lamine', '5+5 Bombeli Seffaf Lamine'),
    ('6+6 Bombeli Seffaf Lamine', '6+6 Bombeli Seffaf Lamine'),
    ('4+4 Bombeli Opak Lamine', '4+4 Bombeli Opak Lamine'),
    ('5+5 Bombeli Opak Lamine', '5+5 Bombeli Opak Lamine'),
    ('6+6 Bombeli Opak Lamine', '6+6 Bombeli Opak Lamine'),
)

GLASS_TYPES_STANDART = (
    ('4+4 Seffaf Lamine', '4+4 Seffaf Lamine'),
    ('5+5 Seffaf Lamine', '5+5 Seffaf Lamine'),
    ('6+6 Seffaf Lamine', '6+6 Seffaf Lamine'),
    ('4+4 Opak Lamine', '4+4 Opak Lamine'),
    ('5+5 Opak Lamine', '5+5 Opak Lamine'),
    ('6+6 Opak Lamine', '6+6 Opak Lamine'),
    ('8 mm Temperli', '8 mm Temperli'),
    ('10 mm Temperli', '10 mm Temperli'),
    ('12 mm Temperli', '12 mm Temperli'),
)
COLOR = (
    ('Ral Boya', 'Ral Boya'),
    ('Mat Eloksal', 'Mat Eloksal'),
    ('Renkli Mat Eloksal', 'Renkli Mat Eloksal'),
    ('304 Kalite Mat Paslanmaz', '304 Kalite Mat Paslanmaz'),
    ('304 Kalite Ayna Paslanmaz', '304 Kalite Ayna Paslanmaz'),
    ('304 Kalite Satine Paslanmaz', '304 Kalite Satine Paslanmaz'),
    ('316 Kalite Mat Paslanmaz', '316 Kalite Mat Paslanmaz'),
    ('316 Kalite Ayna Paslanmaz', '316 Kalite Ayna Paslanmaz'),
    ('316 Kalite Satine Paslanmaz', '316 Kalite Satine Paslanmaz'),
)


class MR30(WorkOrderAbstractModel):
    mr30_type = models.CharField(default='OTOMATİK', max_length=30, choices=MR30_TYPE_DATA,
                                 verbose_name='MR30 Kapı Türü')
    dia = models.IntegerField(default=1600, validators=[MinValueValidator(1600), MaxValueValidator(4000)],
                              verbose_name='Çap')
    trans_height = models.IntegerField(default=1900, validators=[MinValueValidator(1900), MaxValueValidator(4000)],
                                       verbose_name='Geçiş Yüksekliği')
    canopy = models.IntegerField(default=100, validators=[MinValueValidator(100), MaxValueValidator(1500)],
                                 verbose_name='Kanopi')
    # wing_data = models.IntegerField(default=3, choices=WING_DATA, verbose_name='Kanat Sayısı')
    fixed_glass = models.CharField(max_length=100, verbose_name='Sabit Cam', choices=GLASS_TYPES,
                                   default='4bombeliseffaflamine')
    moving_glass = models.CharField(max_length=100, verbose_name='Hareketli Cam', choices=GLASS_TYPES_STANDART,
                                    default='8mmtemperli')
    broken_wing = models.BooleanField(default=False, verbose_name='Kırılan Kanat')
    ground_circle = models.BooleanField(default=False, verbose_name='Yer Çemberi')
    night_sensor = models.BooleanField(default=False, verbose_name='Gece Kalkanı')
    heel_sensor = models.BooleanField(default=False, verbose_name='Dikey Kanat pnomatigi')
    cati_izolasyonu = models.BooleanField(default=False, verbose_name='Cati Izolasyonu')
    hava_perdesi = models.BooleanField(default=False, verbose_name='Hava Perdesi')
    otomasyon_secimi = models.BooleanField(default=False, verbose_name='Otomasyon Secimi')
    spain_key = models.BooleanField(default=False, verbose_name='İspanyolet Kilit')
    stain_arm = models.BooleanField(default=False, verbose_name='Paslanmaz Kol')
    button_pole = models.BooleanField(default=False, verbose_name='Buton Direği')
    # opsiyonlar ve radar aktivasyonları aralarında boş bırakılarak "*_LIST" içerisindeki ilk verilerden olusturulmalı
    # ornek: "acil_stop batarya"
    options = models.CharField('Opsiyonlar', blank=True, null=True, max_length=250, choices=OPTIONS_LIST,
                               default='HMI El Terminali')
    radar_activations = models.CharField('RADAR ve AKTIVASYON SECENEKLERI', blank=True, null=True, max_length=250,
                                         choices=RADAR_ACTIVATION_LIST, default='CombineRadar Safety - Activation')
    colors = models.CharField('Renk', max_length=27, choices=COLOR)

    class Meta:
        db_table = 'MR30'
        verbose_name = 'MR30 Doner Kapilar'
        verbose_name_plural = 'MR30s'

    def __str__(self):
        return f'{self.crm} - {self.company_name} - {self.mr30_type}'
        # crm no ve firma isimleri database ve admin panelinde gozukur.

    def get_absolute_url(self):
        return reverse('mr30:detail', kwargs={'id': self.id})
        # nesnelerimizin adreslemesini yapariz.

    @property  # metodlara alanlara bir ozellikmis gibi erismeyi saglar, fonksiyonu parametre haline getirir.
    def get_display_options(self):
        if self.options:
            return [self.OPTIONS_LIST.get(option) for option in self.options.split(' ')]
        return None

    @property
    def get_display_radar_activations(self):
        if self.radar_activations:
            return [self.RADAR_ACTIVATION_LIST.get(radar) for radar in self.radar_activations.split(' ')]
        return None

    def door(self):
        return self.door_type.split('_')[-1]

    def wing(self):
        for i in self.MR30_TYPE_DATA:
            return i if i == self.mr30_type else ''

    def get_wing_count(self):
        """
        Sabit kanat sayısını hesaplama
        """
        if 'uk' in self.door_type:
            return 3
        elif 'dk' in self.door_type:
            return 4
        else:
            return 0

    def get_wings_info(self):
        """
        Kanat sayılarını alma
        """
        return self.get_wing_count()

imalatlar/apps/sld/models.py
from django.db import models
from django.urls import reverse

from ...common.models import WorkOrderAbstractModel


class SLD(WorkOrderAbstractModel):

    # Burdaki isimlendirmeler js tarafında da aynı şekilde olmalıdır!
    # Herhanbi bi değişiklikte dikkatli olunmalı
    DOOR_TYPES = (
        ('th_standart', 'STANDART TEK HAREKETLI'),
        ('ts_th_standart', 'STANDART TEK SBT. + TEK HRK.'),
        ('ih_standart', 'STANDART IKI HAREKETLI'),
        ('is_ih_standart', 'STANDART IKI SBT. + IKI HRK.'),
        ('th_cam', 'CAM - TEK HAREKETLI'),
        ('ts_th_cam', 'CAM - TEK SBT. + TEK HRK.'),
        ('ih_cam', 'CAM - IKI HAREKETLI'),
        ('is_ih_cam', 'CAM - IKI SBT. + IKI HRK.'),
        ('ih_teleskop', 'TELESKOPIK - IKI HAREKETLI'),
        # ('ih_is_teleskop', 'TELESKOPİK - İKİ HRK. + İKİ SBT.'), # iki hareketli tek sabit olarak duzeltildi.
        ('ih_ts_teleskop', 'TELESKOPIK - IKI HRK. + TEK SBT.'),
        ('dh_teleskop', 'TELESKOPIK - DORT HAREKETLI'),
        ('dh_is_teleskop', 'TELESKOPIK - DORT HRK. + IKI SBT.'),
    )

    OPTIONS_LIST = {
        'konum_anahtari_standart': 'Konum Anahtarı Standart',
        'konum_anahtarı_sivaustu': 'Konum Anahtarı Siva UstU',
        'el_terminali': 'El Terminali',
        'acil_stop': 'Acil Stop',
        'elektronik_kilit': 'Elektronik Kilit',
        'batarya': 'Batarya',
    }
    RADAR_ACTIVATION_LIST = {
        'mikrodalga_radar': 'Mikrodalga Radar',
        'combineRadar_safety_activation': 'CombineRadar Safety - Activation',
        'yaklasim_sensoru': 'Yaklaşım Sensoru',
        'emniyet_fotoseli': 'Emniyet Fotoseli',
    }
    glass = models.CharField('Cam', max_length=25)
    color = models.CharField('Renk', max_length=20)
    opening_direction = models.CharField('Acilis Yonu', max_length=3,
                                         choices=(('sag', 'SAG'), ('sol', 'SOL')), null=True, blank=True)
    ustluk = models.BooleanField('UstlUk Var Mi?', default=False)
    door_type = models.CharField('Kapi Tipi', choices=DOOR_TYPES, max_length=30)
    pass_width = models.PositiveSmallIntegerField('Gecis Genisligi')
    pass_height = models.PositiveSmallIntegerField('Gecis Yüksekligi')
    total_width = models.PositiveSmallIntegerField('Toplam Genislik', null=True, blank=True)
    total_height = models.PositiveSmallIntegerField('Toplam Yükseklik', null=True, blank=True)
    mechanism_width = models.PositiveSmallIntegerField('Mekanizma Genisligi', null=True, blank=True)

    # opsiyonlar ve radar aktivasyonları aralarında boş bırakılarak "*_LIST" içerisindeki ilk verilerden olusturulmalı
    # ornek: "acil_stop batarya"
    options = models.CharField('Opsiyonlar', blank=True, null=True, max_length=250)
    radar_activations = models.CharField('RADAR ve AKTIVASYON SECENEKLERI', blank=True, null=True, max_length=250)

    class Meta:
        db_table = 'SLD'
        verbose_name = 'SLD Kayar Kapilar'
        verbose_name_plural = 'SLDs'

    def __str__(self):
        return f'{self.crm} - {self.company_name} - {self.door_type}' # crm no ve firma isimleri database ve admin panelinde gozukur.

    def get_absolute_url(self):
        return reverse('sld:detail', kwargs={'id': self.id}) # nesnelerimizin adreslemesini yapariz.

    @property # metodlara alanlara bir ozellikmis gibi erismeyi saglar, fonksiyonu parametre haline getirir.
    def get_display_options(self):
        if self.options:
            return [self.OPTIONS_LIST.get(option) for option in self.options.split(' ')]
        return None

    @property
    def get_display_radar_activations(self):
        if self.radar_activations:
            return [self.RADAR_ACTIVATION_LIST.get(radar) for radar in self.radar_activations.split(' ')]
        return None

    def door(self):
        return self.door_type.split('_')[-1]

    def wing(self):
        for i in self.DOOR_TYPE:
            return i if i == self.door_type else ''

    def get_slider_wing_count(self):
        """
        Kayar kanat sayısını hesaplama
        """
        if 'th' in self.door_type:
            return 1
        elif 'ih' in self.door_type:
            return 2
        elif 'dh' in self.door_type:
            return 4

    def get_fixed_wing_count(self):
        """
        Sabit kanat sayısını hesaplama
        """
        if 'ts' in self.door_type:
            return 1
        elif 'is' in self.door_type:
            return 2
        else:
            return 0

    def get_wings_info(self):
        """
        Kanat sayılarını alma
        """
        return self.get_slider_wing_count(), self.get_fixed_wing_count()

imalatlar/apps/mr30/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms

from .models import MR30


class MR30Form(forms.ModelForm):
    class Meta:
        model = MR30
        fields = "__all__"



        widgets = {
            'delivery_date': DatePickerInput(format='%d/%m/%Y',
                                             attrs={'placeholder': 'teslim tarihi', 'class': 'form-control'}),
        }


# fields = [
#             'company_name',
#             'crm',
#             'billing_adress', 'delivery_date',
#             'delivery_adress',
#             'delivery_type',
#             'created_time',
#             'has_chest', # sandikli mi
#             'glass', # GLASS_TYPES
#             'color', # COLORS
#             'notes',
#             'drawing',
#             'control',
#             'manufacturing_chief',

#             'mr30_type',
#             'dia',
#             'trans_height',
#             'canopy',
#             'wing_data', # WING_DATA
#             'fixed_glass', # GLASS_TYPES
#             'moving_glass', # GLASS_TYPES_STANDART

#             'broken_wing',
#             'ground_circle',
#             'night_sensor',
#             'heel_sensor',
#             'cati_izolasyonu',
#             'hava_perdesi',
#             'otomasyon_secimi',
#             'spain_key',
#             'stain_arm',
#             'button_pole',
#             'options', 'radar_activations', colors
#         ]

imalatlar/apps/mr30/views.py
import subprocess

from django.contrib.auth.views import login_required
from django.contrib.messages import success, error
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from django.template.loader import render_to_string

# from ...utils.thread_mail import send_html_mail
from imalatlar.settings import ALLOWED_HOSTS
from .forms import MR30Form
from .models import MR30


@login_required
def detail_view(request, id):
    work_order = get_object_or_404(MR30, id=id)
    return render(request, 'mr30/detail.html', {'work_order': work_order})


@login_required
def create_view(request):
    if request.method == 'POST':
        form = MR30Form(request.POST)  # request.post un icinden gelen veriler ile bana bir form hazirla, onuda form a atadik

        if form.is_valid():  # kayit valid ise asagidaki islemlere gecilir degilse, else blogu calisir
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            success(request, f'{instance.crm} başarıyla oluşturuldu.')
            return redirect('mr30:list')
        else:
            error(request, 'Lütfen formu eksiksiz doldurduğunuza emin olun!')
    elif request.method == 'GET':
        form = MR30Form()
    context = {
        'form': form
    }
    return render(request, 'mr30/create.html', context)


@login_required
def list_view(request):
    return render(request, 'mr30/list.html', {'list': MR30.objects.all()})


@login_required
def send_mail(request, id):
    # tmp dizininin Windowsta olmamasından dolayı windowsta çalışmayabilir
    # wkhtmktopdf'i sunucuya kurmayı unutmayın!
    # Localde çalışırken default 8000 portunda çalıştırın!
    door = get_object_or_404(MR30, id=id)

    curr_url = ALLOWED_HOSTS[0].replace('http://', '').replace('https://', '') if ALLOWED_HOSTS else '127.0.0.1:8000'
    html = render_to_string('sld/detail.html', {'work_order': door, 'print': True}).replace('/static/',
                                                                                            f'http://{curr_url}/static/')

    with open(f'/tmp/{door.crm}.html', 'w') as f:
        f.write(html)

    pdf_file = f'/tmp/sld_{door.door_type}_{door.id}.pdf'
    subprocess.run([
        'wkhtmltopdf',
        '--javascript-delay', '2000',
        '--viewport-size', '1024x768',
        '--load-error-handling', 'ignore',
        f'/tmp/{door.crm}.html',
        pdf_file
    ])
    send_html_mail(
        f'{door.crm} - {door.get_door_type_display()}',
        '<p>Kapının teknik detayları ekteki pdftedir.</p>',
        file=pdf_file
    )
    return HttpResponse('Mail Başarıyla gönderildi.')

imalatlar/apps/mr30/templates/mr30/detail.html
{% extends 'base.html' %}
{% load  static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/sld/detail.css' %}">

{% endblock %}

{% block body %}
    {#    <div style="margin-top: -90px">#}

    <div class="container fixed-top bg-white">
        <div class="row navbar navbar-expand-lg navbar-light bg-light">
            <nav class="nav">
                <a class="nav-link active" aria-current="page"
                   href="{% url 'home:kapilar' %}">KAPI TIPLERI</a>
                <a class="nav-link active" aria-current="page"
                   href="{% url 'home:aboutmr30' %}">MR30</a>

                <a class="nav-link active" style="color:black;"
                   aria-current="page">MR30 {{ work_order.get_door_type_display }} DONER KAPI</a>
                <a class="nav-link active" style="color:black;" aria-current="page">Detay{{ work_order.id }}</a>

            </nav>
        </div>


        <div class="row navbar navbar-expand-lg navbar-light bg-white" style="height: 25px;">
            <nav class="nav justify-content-end">
                <a class="nav-link" aria-current="page" href="javascript:printDiv('divYazdir');">
                    Yazdir</a>
                <a class="nav-link" aria-current="page" target="_blank"
                   href="{% url 'mr30:send_mail' id=work_order.id %}">Mail Gonder</a>

            </nav>

        </div>
        <hr>
    </div>






    {##}
    {#    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">#}
    {#        <div class="container-fluid">#}
    {#            <div class="row">#}
    {#                <div class="col" style="display: inherit">#}
    {#                    <div>#}
    {#                        <a href="{% url 'home:kapilar' %}">KAPI TIPLERI</a> / <a#}
    {#                            href="{% url 'home:aboutsld' %}">SLD</a> /#}
    {#                        Detay / {{ work_order.id }}<br>#}
    {#                    </div>#}
    {#    <div class="col" style="text-align: right;">#}
    {#        <a target="_blank" href="{% url 'sld:send_mail' id=work_order.id %}">#}
    {#            <i class="fa fa-mail-forward">Mail Gönder</i>#}
    {#        </a>#}
    {##}
    {#        <a class="text-dark" href="javascript:printDiv('divYazdir');">#}
    {#            <img src="{% static 'img/yazdir.png' %}" width="30" height="30" alt="">#}
    {#            <i>Yazdır</i>#}
    {#        </a>#}
    {##}
    {#    </div>#}
    {##}
    {#    <div>#}
    {#        <b style="color:black;">SLD {{ work_order.get_door_type_display }} KAYAR KAPI</b>#}
    {#    </div>#}
    {#                    <div>#}
    {#                        Oluşturan {% firstof work_order.user.get_full_name  work_order.user.username %}#}
    {#                        {{ work_order.created_time }}#}
    {#                    </div>#}
    {##}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </nav>#}


    {#        <div class="row">#}
    {#            <div class="col-md-12" style="display: inherit">#}
    {#                <div class="col-md-5">#}
    {#                    <a href="{% url 'home:kapilar' %}">KAPI TIPLERI</a> / <a href="{% url 'home:aboutsld' %}">SLD</a> /#}
    {#                    Detay / {{ work_order.id }}#}
    {#                </div>#}
    {#                <div class="col-md-2 offset-4">#}
    {#                    <a target="_blank" href="{% url 'sld:send_mail' id=work_order.id %}">#}
    {#                        <i class="fa fa-mail-forward">Mail Gönder</i>#}
    {#                    </a>#}
    {#                </div>#}
    {#                <div class="col-md-1"><a class="text-dark" href="javascript:printDiv('divYazdir');">#}
    {#                    <img src="{% static 'img/yazdir.png' %}" width="30" height="30" alt="">#}
    {#                    <i>Yazdır</i>#}
    {#                </a>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#        <div class="row">#}
    {#            <div class="col-md-8">#}
    {#                <b style="color:black;">SLD {{ work_order.get_door_type_display }} KAYAR KAPI</b>#}
    {#            </div>#}
    {#            <div class="col-md-4" style="text-align: right;">#}
    {#                Oluşturan {% firstof work_order.user.get_full_name  work_order.user.username %}#}
    {#                <br>#}
    {#                {{ work_order.created_time }}#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
    {% include 'sld/parts/'|add:work_order.door_type|add:'.html' %}
{% endblock body %}

{% block extra_script %}
    {#    <script type="text/javascript">#}
    {#        function printDiv(divName) {#}
    {#            window.print();#}
    {#        }#}
    {##}
    {#        $('.nav-tabs li').click(function () {#}
    {#            $('.nav-tabs li').removeClass('active');#}
    {#            $(this).addClass('active');#}
    {#        });#}
    {#    </script>#}
{% endblock %}

imalatlar/apps/mr30/templates/mr30/list.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    {% include 'navbar.html' %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    <br>
    <section class="services-area section-gap">
        <div class="container">
            <a href="{% url 'home:aboutmr30' %}"><strong>MR30 ISLEM TURLERI</strong></a> | <a
                href="{% url 'mr30:create' %}"><strong>MR30 YENI OLUSTUR</strong></a>
            <hr>
            <div class="col-md-12" style="text-align: right;">
                <h4>MR30 Uretim is Emirleri</h4>
            </div>
            <br>
            <div class="card">
                <div class="card-cody">
                    <div class="table-responsive-md">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>CRM NO</th>
                                <th>Firma</th>
                                <th>Teslim Tarihi</th>
                                <th>Kayıt Zamanı</th>
                                <th>Kapı Türü</th>
                                <th>Detaylar</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for work_order in list %}
                                <tr>
                                    <th>{{ work_order.crm }}</th>
                                    <td>{{ work_order.company_name }}</td>
                                    <td>{{ work_order.delivery_date }}</td>
                                    <td>{{ work_order.created_time|timesince }} önce</td>
                                    <td>{{ work_order.get_door_type_display|title }}</td>
                                    <td><a href="{% url 'mr30:detail' id=work_order.id %}">
                                        <div class="btn btn-outline-success">Görüntüle</div>
                                    </a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <br><br>
            {% include 'footer.html' %}
        </div>
    </section>

{% endblock %}