imalatlar/apps/home/urls.py
from django.urls import path

from .views import *

app_name = "home"

urlpatterns = [
    path('', home_view, name='home'),
    path('kapilar/',kapilar_view,name='kapilar'),
    path('about_sld/', aboutsld_view, name='aboutsld'),
    path('about_mr30/', aboutmr30_view, name='aboutmr30'),
    path('401/', view_401,name='401'),
]

imalatlar/apps/sld/urls.py
from django.urls import path
from .views import detail_view, create_view, list_view, make_pdf

app_name = 'sld'
urlpatterns = [
    path('goruntule/<id>', detail_view, name='detail'),
    path('olustur', create_view, name='create'),
    path('liste', list_view, name='list'),
    path('gonder/<id>', make_pdf, name='make_pdf')
]

imalatlar/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("imalatlar.apps.home.urls", namespace='home')),
    path('sld/', include("imalatlar.apps.sld.urls", namespace='sld')),
    path('mr30/', include("imalatlar.apps.mr30.urls", namespace='mr30')),
    path('user/', include("imalatlar.apps.user.urls", namespace='user')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

imalatlar/apps/sld/models.py
from django.db import models
from django.urls import reverse

from ...common.models import WorkOrderAbstractModel


class SLD(WorkOrderAbstractModel):

    # Burdaki isimlendirmeler js tarafında da aynı şekilde olmalıdır!
    # Herhanbi bi değişiklikte dikkatli olunmalı
    DOOR_TYPES = (
        ('th_standart', 'STANDART TEK HAREKETLI'),
        ('ts_th_standart', 'STANDART TEK SBT. + TEK HRK.'),
        ('ih_standart', 'STANDART IKI HAREKETLI'),
        ('is_ih_standart', 'STANDART IKI SBT. + IKI HRK.'),
        ('th_cam', 'CAM - TEK HAREKETLI'),
        ('ts_th_cam', 'CAM - TEK SBT. + TEK HRK.'),
        ('ih_cam', 'CAM - IKI HAREKETLI'),
        ('is_ih_cam', 'CAM - IKI SBT. + IKI HRK.'),
        ('ih_teleskop', 'TELESKOPIK - IKI HAREKETLI'),
        # ('ih_is_teleskop', 'TELESKOPİK - İKİ HRK. + İKİ SBT.'), # iki hareketli tek sabit olarak duzeltildi.
        ('ih_ts_teleskop', 'TELESKOPIK - IKI HRK. + TEK SBT.'),
        ('dh_teleskop', 'TELESKOPIK - DORT HAREKETLI'),
        ('dh_is_teleskop', 'TELESKOPIK - DORT HRK. + IKI SBT.'),
    )

    OPTIONS_LIST = {
        'konum_anahtari_standart': 'Konum Anahtarı Standart',
        'konum_anahtarı_sivaustu': 'Konum Anahtarı Siva UstU',
        'el_terminali': 'El Terminali',
        'acil_stop': 'Acil Stop',
        'elektronik_kilit': 'Elektronik Kilit',
        'batarya': 'Batarya',
    }
    RADAR_ACTIVATION_LIST = {
        'mikrodalga_radar': 'Mikrodalga Radar',
        'combineRadar_safety_activation': 'CombineRadar Safety - Activation',
        'yaklasim_sensoru': 'Yaklaşım Sensoru',
        'emniyet_fotoseli': 'Emniyet Fotoseli',
    }
    glass = models.CharField('Cam', max_length=25)
    color = models.CharField('Renk', max_length=20)
    opening_direction = models.CharField('Acilis Yonu', max_length=3,
                                         choices=(('sag', 'SAG'), ('sol', 'SOL')), null=True, blank=True)
    ustluk = models.BooleanField('UstlUk Var Mi?', default=False)
    door_type = models.CharField('Kapi Tipi', choices=DOOR_TYPES, max_length=30)
    pass_width = models.PositiveSmallIntegerField('Gecis Genisligi')
    pass_height = models.PositiveSmallIntegerField('Gecis Yüksekligi')
    total_width = models.PositiveSmallIntegerField('Toplam Genislik', null=True, blank=True)
    total_height = models.PositiveSmallIntegerField('Toplam Yükseklik', null=True, blank=True)
    mechanism_width = models.PositiveSmallIntegerField('Mekanizma Genisligi', null=True, blank=True)

    # opsiyonlar ve radar aktivasyonları aralarında boş bırakılarak "*_LIST" içerisindeki ilk verilerden olusturulmalı
    # ornek: "acil_stop batarya"
    options = models.CharField('Opsiyonlar', blank=True, null=True, max_length=250)
    radar_activations = models.CharField('RADAR ve AKTIVASYON SECENEKLERI', blank=True, null=True, max_length=250)

    class Meta:
        db_table = 'SLD'
        verbose_name = 'SLD Kayar Kapilar'
        verbose_name_plural = 'SLDs'

    def __str__(self):
        return f'{self.crm} - {self.company_name} - {self.door_type}' # crm no ve firma isimleri database ve admin panelinde gozukur.

    def get_absolute_url(self):
        return reverse('sld:detail', kwargs={'id': self.id}) # nesnelerimizin adreslemesini yapariz.

    @property # metodlara alanlara bir ozellikmis gibi erismeyi saglar, fonksiyonu parametre haline getirir.
    def get_display_options(self):
        if self.options:
            return [self.OPTIONS_LIST.get(option) for option in self.options.split(' ')]
        return None

    @property
    def get_display_radar_activations(self):
        if self.radar_activations:
            return [self.RADAR_ACTIVATION_LIST.get(radar) for radar in self.radar_activations.split(' ')]
        return None

    def door(self):
        return self.door_type.split('_')[-1]

    def wing(self):
        for i in self.DOOR_TYPE:
            return i if i == self.door_type else ''

    def get_slider_wing_count(self):
        """
        Kayar kanat sayısını hesaplama
        """
        if 'th' in self.door_type:
            return 1
        elif 'ih' in self.door_type:
            return 2
        elif 'dh' in self.door_type:
            return 4

    def get_fixed_wing_count(self):
        """
        Sabit kanat sayısını hesaplama
        """
        if 'ts' in self.door_type:
            return 1
        elif 'is' in self.door_type:
            return 2
        else:
            return 0

    def get_wings_info(self):
        """
        Kanat sayılarını alma
        """
        return self.get_slider_wing_count(), self.get_fixed_wing_count()

imalatlar/apps/sld/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms

from .models import SLD


class SLDForm(forms.ModelForm):
    class Meta:
        model = SLD
        fields = "__all__"



        # fields = [
        #     'crm', 'company_name', 'billing_address', 'delivery_address', 'delivery_date', 'delivery_type', 'has_chest',
        #     'glass', 'color', 'notes', 'drawing', 'control', 'manufacturing_chief', 'door_type', 'pass_width',
        #     'pass_height', 'pass_height', 'ustluk', 'total_width', 'total_height', 'mechanism_width',
        #     'opening_direction', 'options', 'radar_activations',
        # ]
        widgets = {
            # 'crm': forms.TextInput(attrs={'placeholder': 'crm no', 'class': 'form-control'}),
            # 'crm': forms.TextInput,
            # 'company_name': forms.TextInput(attrs={'placeholder': 'firma adi', 'class': 'form-control'}),
            # 'billing_address': forms.TextInput(attrs={'placeholder': 'fatura adresi', 'class': 'form-control'}),
            # 'delivery_address': forms.TextInput(attrs={'placeholder': 'sevk adresi', 'class': 'form-control'}),
            'delivery_date': DatePickerInput(format='%d/%m/%Y',
                                             attrs={'placeholder': 'teslim tarihi', 'class': 'form-control'}),
            # 'delivery_type': forms.Select(attrs={'placeholder': 'Teslim sekli', 'class': 'form-control'}),
            # 'glass': forms.Select(attrs={'placeholder': 'cam', 'class': 'form-control'}),
            #
            # 'notes': forms.CharField(required=False, widget=forms.Textarea(attrs={
            #     "cols": 50,
            #     "rows": 20,
            #     "label": 'firma bilgileri',
            #     'class': 'form-control',
            # })),
            # 'pass_width': forms.NumberInput(attrs={'placeholder': 'gecis genisligi', 'class': 'form-control'})
        }

imalatlar/apps/sld/views.py
import subprocess

from django.contrib.auth.views import login_required
from django.contrib.messages import success, error
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from django.template.loader import render_to_string

from ...utils.thread_mail import send_html_mail
from imalatlar.settings import ALLOWED_HOSTS
from .forms import SLDForm
from .models import SLD


@login_required
def detail_view(request, id):
    work_order = get_object_or_404(SLD, id=id)
    return render(request, 'sld/detail.html', {'work_order': work_order})


@login_required
def create_view(request):
    if request.method == 'POST':
        form = SLDForm(
            request.POST)  # request.post un icinden gelen veriler ile bana bir form hazirla, onuda form a atadik

        if form.is_valid():  # kayit valid ise asagidaki islemlere gecilir degilse, else blogu calisir
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            success(request, f'{instance.crm} başarıyla oluşturuldu.')
            return redirect('sld:list')
        else:
            error(request, 'Lütfen formu eksiksiz doldurduğunuza emin olun!')
    elif request.method == 'GET':
        form = SLDForm()
    context = {
        'form': form
    }
    return render(request, 'sld/create.html', context)


@login_required
def list_view(request):
    return render(request, 'sld/list.html', {'list': SLD.objects.all()})


@login_required
def make_pdf(request, id):
    door = get_object_or_404(SLD, id=id)

    curr_url = ALLOWED_HOSTS[0].replace('http://', '').replace('https://', '') if ALLOWED_HOSTS else '127.0.0.1:8000'
    html = render_to_string('sld/detail.html', {'work_order': door, 'print': True}).replace('/static/',
                                                                                            f'http://{curr_url}/static/')

    with open(f'/tmp/{door.crm}.html', 'w') as f:
        f.write(html)

    pdf_file = f'/tmp/sld_{door.door_type}_{door.id}.pdf'
    subprocess.run([
        'wkhtmltopdf',
        '--javascript-delay', '2000',
        '--viewport-size', '1024x768',
        '--load-error-handling', 'ignore',
        f'/tmp/{door.crm}.html',
        pdf_file
    ])



# @login_required
# def send_mail(request, id):
#     # tmp dizininin Windowsta olmamasından dolayı windowsta çalışmayabilir
#     # wkhtmktopdf'i sunucuya kurmayı unutmayın!
#     # Localde çalışırken default 8000 portunda çalıştırın!
#     door = get_object_or_404(SLD, id=id)
#
#     curr_url = ALLOWED_HOSTS[0].replace('http://', '').replace('https://', '') if ALLOWED_HOSTS else '127.0.0.1:8000'
#     html = render_to_string('sld/detail.html', {'work_order': door, 'print': True}).replace('/static/',
#                                                                                             f'http://{curr_url}/static/')
#
#     with open(f'/tmp/{door.crm}.html', 'w') as f:
#         f.write(html)
#
#     pdf_file = f'/tmp/sld_{door.door_type}_{door.id}.pdf'
#     subprocess.run([
#         'wkhtmltopdf',
#         '--javascript-delay', '2000',
#         '--viewport-size', '1024x768',
#         '--load-error-handling', 'ignore',
#         f'/tmp/{door.crm}.html',
#         pdf_file
#     ])
#     send_html_mail(
#         f'{door.crm} - {door.get_door_type_display()}',
#         '<p>Kapının teknik detayları ekteki pdftedir.</p>',
#         file=pdf_file
#     )
#     return HttpResponse('Mail Başarıyla gönderildi.')

imalatlar/apps/sld/templates/sld/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}



{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/sld/form.css' %}">
{% endblock %}

{% block body %}

    {#    {% include 'navbar.html' %}#}
    {#    <br>#}
    <div class="container">
        <div class="row">
            <div class="col-md-5"><h4>İŞ EMRİ</h4></div>
            <div class="col-md-7" style="text-align: right;"><h4>SLD KAYAR KAPI</h4></div>
        </div>
        <hr>
        <div class="card">
            <div class="card-body">
                                {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ field.label }} | {{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger" role="alert">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                <div class="container">
                    <form method="POST" action="{% url 'sld:create' %}">
                        {% csrf_token %}

                        {% load bootstrap4 %}
                        {% bootstrap_css %}
                        {% bootstrap_javascript jquery='full' %}
                        {{ form.media }}

                        <div class="accordion col-12" id="accordionPanelsStayOpenExample">
                            <div class="accordion-item ">
                                <h4 class="accordion-header" id="panelsStayOpen-headingOne">
                                    <button class="accordion-button col-12" type="button"
                                            data-bs-toggle="collapse"
                                            data-bs-target="#panelsStayOpen-collapseOne"
                                            aria-expanded="true"
                                            aria-controls="panelsStayOpen-collapseOne">
                                        GENEL BILGILER
                                    </button>
                                </h4>
                                <div id="panelsStayOpen-collapseOne"
                                     class="accordion-collapse collapse show"
                                     aria-labelledby="panelsStayOpen-headingOne">
                                    <div class="accordion-body">

                                        <div class="row">
                                            <div class="col-4">
                                                {{ form.user|as_crispy_field }}
                                            </div>
                                            <div class="col-4">
                                                {{ form.crm|as_crispy_field }}
                                            </div>
                                            <div class="col-4">
                                                {{ form.company_name|as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-4">
                                                {{ form.billing_address|as_crispy_field }}
                                            </div>
                                            <div class="col-4">
                                                {{ form.delivery_address|as_crispy_field }}
                                            </div>
                                            <div class="col-4">
                                                {{ form.delivery_date|as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-9">
                                                {{ form.delivery_type|as_crispy_field }}
                                            </div>
                                            <div class="col-3">
                                                {{ form.has_chest|as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                {{ form.glass|as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                {{ form.color|as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                {{ form.notes|as_crispy_field }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-4">
                                                {{ form.drawing|as_crispy_field }}
                                            </div>
                                            <div class="col-4">
                                                {{ form.control|as_crispy_field }}
                                            </div>
                                            <div class="col-4">
                                                {{ form.manufacturing_chief|as_crispy_field }}
                                            </div>
                                        </div>


                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h4 class="accordion-header" id="panelsStayOpen-headingTwo">
                                        <button class="accordion-button collapsed col-12" type="button"
                                                data-bs-toggle="collapse"
                                                data-bs-target="#panelsStayOpen-collapseTwo"
                                                aria-expanded="false"
                                                aria-controls="panelsStayOpen-collapseTwo">
                                            KAPI SECIMI
                                        </button>
                                    </h4>
                                    <div id="panelsStayOpen-collapseTwo"
                                         class="accordion-collapse collapse"
                                         aria-labelledby="panelsStayOpen-headingTwo">
                                        <div class="accordion-body">
                                            <div class="row">
                                                <div class="col-12">
                                                    {{ form.door_type|as_crispy_field }}
                                                </div>
                                            </div>
                                            <br><br>
                                            <div class="row">
                                                <div class="col">
                                                    {{ form.pass_width|as_crispy_field }}
                                                </div>
                                                <div class="col">
                                                    {{ form.pass_height|as_crispy_field }}
                                                </div>
                                                <div class="col">
                                                    {{ form.opening_direction|as_crispy_field }}
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col">
                                                    {{ form.ustluk|as_crispy_field }}
                                                </div>
                                                <div class="col">
                                                    {{ form.total_width|as_crispy_field }}
                                                </div>
                                                <div class="col">
                                                    {{ form.total_height|as_crispy_field }}
                                                </div>
                                                <div class="col">
                                                    {{ form.mechanism_width|as_crispy_field }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h4 class="accordion-header" id="panelsStayOpen-headingThree">
                                        <button class="accordion-button collapsed col-12" type="button"
                                                data-bs-toggle="collapse"
                                                data-bs-target="#panelsStayOpen-collapseThree"
                                                aria-expanded="false"
                                                aria-controls="panelsStayOpen-collapseThree">
                                            KAPI ICIN OPSIYON SECIMI
                                        </button>
                                    </h4>
                                    <div id="panelsStayOpen-collapseThree"
                                         class="accordion-collapse collapse"
                                         aria-labelledby="panelsStayOpen-headingThree">
                                        <div class="accordion-body">
                                            <div class="row">
                                                <div class="col-12">
                                                    {{ form.options|as_crispy_field }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h4 class="accordion-header" id="panelsStayOpen-headingFour">
                                        <button class="accordion-button collapsed col-12" type="button"
                                                data-bs-toggle="collapse"
                                                data-bs-target="#panelsStayOpen-collapseFour"
                                                aria-expanded="false"
                                                aria-controls="panelsStayOpen-collapseThree">
                                            RADAR ve AKTIVASYON SECIMI
                                        </button>
                                    </h4>
                                    <div id="panelsStayOpen-collapseFour"
                                         class="accordion-collapse collapse"
                                         aria-labelledby="panelsStayOpen-headingFour">
                                        <div class="accordion-body">
                                            <div class="row">
                                                <div class="col-12">
                                                    {{ form.radar_activations|as_crispy_field }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div style="text-align: center;">
                            <input type="submit" value="Oluştur" class="btn btn-primary btn-sm"/>
                        </div>
                    </form>
                </div>
            </div>
            <br>
            {% include 'footer.html' %}
        </div>

    </div>
{% endblock body %}

{% block extra_script %}
    <script src="{% static 'js/doors/sld/form.js' %}"></script>
{% endblock %}

imalatlar/apps/sld/templates/sld/detail.html
{% extends 'base.html' %}
{% load  static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/sld/detail.css' %}">

{% endblock %}

{% block body %}

    <div class="container fixed-top bg-white">
        <div class="row navbar navbar-expand-lg navbar-light bg-light">
            <nav class="nav">
                <a class="nav-link active" aria-current="page"
                   href="{% url 'home:kapilar' %}">KAPI TIPLERI</a>
                <a class="nav-link active" aria-current="page"
                   href="{% url 'home:aboutsld' %}">SLD</a>

                <a class="nav-link active" style="color:black;"
                   aria-current="page">SLD {{ work_order.get_door_type_display }} KAYAR KAPI</a>
                <a class="nav-link active" style="color:black;" aria-current="page">Detay{{ work_order.id }}</a>

            </nav>
        </div>
        <div class="row navbar navbar-expand-lg navbar-light bg-white" style="height: 25px;">
            <nav class="nav justify-content-end">
                <a class="nav-link" aria-current="page" href="javascript:printDiv('divYazdir');">Yazdir</a>
                <a class="nav-link" aria-current="page" target="_blank"
                   href="{% url 'sld:make_pdf' id=work_order.id %}">Mail Gonder</a>

            </nav>
        </div>
        <hr>
    </div>

    {% include 'sld/parts/'|add:work_order.door_type|add:'.html' %}
{% endblock body %}

{% block extra_script %}
    <script type="text/javascript">
        function printDiv(divName) {
            window.print();
        }

        $('.nav-tabs li').click(function () {
            $('.nav-tabs li').removeClass('active');
            $(this).addClass('active');
        });
    </script>
{% endblock %}

imalatlar/apps/sld/templates/sld/list.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    {% include 'navbar.html' %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    <br>
    <section class="services-area section-gap">
        <div class="container">
            <a href="{% url 'home:aboutsld' %}"><strong>SLD ISLEM TURLERI</strong></a> | <a
                href="{% url 'sld:create' %}"><strong>SLD YENI OLUSTUR</strong></a>
            <hr>
            <div class="col-md-12" style="text-align: right;">
                <h4>SLD Uretim is Emirleri</h4>
            </div>
            <br>
            <div class="card">
                <div class="card-cody">
                    <div class="table-responsive-md">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>CRM NO</th>
                                <th>Firma</th>
                                <th>Teslim Tarihi</th>
                                <th>Kayıt Zamanı</th>
                                <th>Kapı Türü</th>
                                <th>Detaylar</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for work_order in list %}
                                <tr>
                                    <th>{{ work_order.crm }}</th>
                                    <td>{{ work_order.company_name }}</td>
                                    <td>{{ work_order.delivery_date }}</td>
                                    <td>{{ work_order.created_time|timesince }} önce</td>
                                    <td>{{ work_order.get_door_type_display|title }}</td>
                                    <td><a href="{% url 'sld:detail' id=work_order.id %}">
                                        <div class="btn btn-outline-success">Görüntüle</div>
                                    </a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <br><br>
            {% include 'footer.html' %}
        </div>
    </section>

{% endblock %}