imalatlar/apps/sld/urls.py
from django.urls import path
from .views import detail_view, create_view, list_view, make_pdf

app_name = 'sld'
urlpatterns = [
    path('goruntule/<id>', detail_view, name='detail'),
    path('olustur', create_view, name='create'),
    path('liste', list_view, name='list'),
    path('gonder/<id>', make_pdf, name='make_pdf')
]

imalatlar/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("imalatlar.apps.home.urls", namespace='home')),
    path('sld/', include("imalatlar.apps.sld.urls", namespace='sld')),
    path('mr30/', include("imalatlar.apps.mr30.urls", namespace='mr30')),
    path('user/', include("imalatlar.apps.user.urls", namespace='user')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/kapilar/aboutmr30.html
{% extends 'base.html' %}
{% load static %}


    {% block body %}
    {% include 'navbar.html' %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4>MR30 KAPILAR / İşlem Türleri</h4>
                <hr>
            </div>
        </div>
        <div class="filters-content" style="text-align: center;">
            <div class="row grid" style="text-align: center;">
                <div class="single-portfolio col-sm-2 all raster">
                    <div class="relative">
                        <div class="thumb">
                            <a href="{% url 'sld:create' %}">
                                <div class="overlay overlay-bg"></div>
                                <img class="image img-fluid" src="{% static 'img/mr30.jpg' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="p-inner">
                        <a href="{% url 'mr30:create' %}"><h4 class="text-info" class="text-info"
                                                             style="text-align: center;">İmalat Oluştur</h4></a>
                    </div>
                </div>
                <div class="single-portfolio col-sm-2 all raster">
                    <div class="relative">
                        <div class="thumb">
                            <a href="{% url 'mr30:list' %}">
                                <div class="overlay overlay-bg"></div>
                                <img class="image img-fluid" src="{% static 'img/mr30.jpg' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="p-inner">
                        <a href="{% url 'mr30:list' %}"><h4 class="text-info" class="text-info"
                                                           style="text-align: center;">İmalat Geçmişi</h4></a>
                    </div>
                </div>
            </div>
        </div>
        <br><br><br>
    {% include 'footer.html' %}
    </div>


    {% endblock body %}

templates/kapilar/aboutsld.html
{% extends 'base.html' %}
{% load static %}


    {% block body %}
    {% include 'navbar.html' %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4>SLD KAPILAR / İşlem Türleri</h4>
                <hr>
            </div>
        </div>
        <div class="filters-content" style="text-align: center;">
            <div class="row grid" style="text-align: center;">
                <div class="single-portfolio col-sm-2 all raster">
                    <div class="relative">
                        <div class="thumb">
                            <a href="{% url 'sld:create' %}">
                                <div class="overlay overlay-bg"></div>
                                <img class="image img-fluid" src="{% static 'img/sld.jpg' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="p-inner">
                        <a href="{% url 'sld:create' %}"><h4 class="text-info" class="text-info"
                                                             style="text-align: center;">İmalat Oluştur</h4></a>
                    </div>
                </div>
                <div class="single-portfolio col-sm-2 all raster">
                    <div class="relative">
                        <div class="thumb">
                            <a href="{% url 'sld:list' %}">
                                <div class="overlay overlay-bg"></div>
                                <img class="image img-fluid" src="{% static 'img/sld.jpg' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="p-inner">
                        <a href="{% url 'sld:list' %}"><h4 class="text-info" class="text-info"
                                                           style="text-align: center;">İmalat Geçmişi</h4></a>
                    </div>
                </div>
            </div>
        </div>
        <br><br><br>
    {% include 'footer.html' %}
    </div>


    {% endblock body %}