imalatlar/apps/home/urls.py
from django.urls import path

from .views import *

app_name = "home"

urlpatterns = [
    path('', home_view, name='home'),
    path('kapilar/',kapilar_view,name='kapilar'),
    path('about_sld/', aboutsld_view, name='aboutsld'),
    path('about_mr30/', aboutmr30_view, name='aboutmr30'),
    path('401/', view_401,name='401'),
]

imalatlar/apps/user/urls.py
from django.urls import path
from .views import login_view,logout_view


app_name = "user"

urlpatterns = [
    path('giris/',login_view,name='login'),
    path('cikis/',logout_view,name="logout"),
]

imalatlar/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("imalatlar.apps.home.urls", namespace='home')),
    path('sld/', include("imalatlar.apps.sld.urls", namespace='sld')),
    path('mr30/', include("imalatlar.apps.mr30.urls", namespace='mr30')),
    path('user/', include("imalatlar.apps.user.urls", namespace='user')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

imalatlar/apps/home/models.py
from django.db import models

# Create your models here.

imalatlar/apps/home/views.py
from django.shortcuts import render, redirect

def home_view(request):
    if request.user.is_authenticated:
        return redirect('home:kapilar')
    return render(request,'home.html')

def kapilar_view(request):
    return render(request,'kapilar.html')


def aboutsld_view(request):
    return render(request, "kapilar/aboutsld.html")

def aboutmr30_view(request):
    return render(request, "kapilar/aboutmr30.html")


def view_401(request):

    return render(request,'401.html',{})

templates/401.html
{% block body %}

    <section class="services-area section-gap">
        <div class="container">
            <b>
                <h1>401 Hatası</h1>
                <p>Http durum kodu hatalarından birisi olan 401 hatası kullanıcıların kimliğinin yada hesabının sunucu</p>
                <p>tarafından doğrulanmaması sonucunda ortaya çıkar. Örnek olarak girmek istediğiniz sayfaya sadece üyeler</p>
                <p>girebiliyor fakat siz üye değilseniz bu hatayı alabilirsiniz. Ya da başka bir açıdan bakarsak admin</p>
                <p>paneli sayfasına üye iken girmek isterseniz 401 hata kodunu alabilirsiniz.</p>
            </b>
        </div>
    </section>

{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% block extra_css %}
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{#{% block body %}{% endblock %}#}

<!-- Sonuclarin goruntulenmesi sirasinda ust kisimda bosluk olusturuyor. -->
<div style="margin-top: 100px" class="container-fluid">
    {% block body %}
    {% endblock body %}

</div>

{#    {% block body %}#}
{#    {% endblock body %}#}


    <script src="{% static '/js/bootstrap.js' %}"></script>
    <script src="{% static '/js/jquery-3.5.1.min.js' %}"></script>



{% block extra_script %}
{% endblock %}

</body>

templates/footer.html
<div class="container">
    <hr>
    {% if  request.user.is_authenticated %}
        <ul class="list-inline">
            <li class="list-inline-item"><a href="https://www.arslanyapi.com.tr/" target="_blank"><p>&copy; Arslan yapi
                ---
                2021</p></a></li>
            <li class="list-inline-item"><strong><code>&lt;{{ request.user.get_username }}&gt;</code></strong></li>
            <li class="list-inline-item"><a href="{% url 'user:logout' %}">CIKIS YAP</a></li>
        </ul>
    {% endif %}
    <p class="fw-lighter">Bu imalat programi @Arslanyapi icin hazirlanmistir, izinsiz kullanilmasi yasaktir.</p>
</div>

templates/home.html
{% extends 'base.html' %}
{% load static %}

<title>{% block title %}GIRIS SAYFASI{% endblock %}</title>

{% block body %}
    <div class="container-fluid mt-3">
        <div class="bg-success">
            <img src="{% static 'img/metaxdoor-doner-kapı-revolving-door.jpg' %}" alt="imalat resmi"
                 style="max-height: 7rem;"/>
        </div>
        <div class="card border-success mt-4 rounded mx-auto d-block" style="max-width: 19rem;">
            <div class="card-header"><h5>imalat programi</h5></div>
            <div class="card-body text-success">
                <h6 class="card-title">HTM METAXDOOR GmbH</h6>
                <p class="card-text">METAXDOOR imalat programi kullanmak icin asagidaki buton ile giris
                    yapalim</p><br><br><br>
                <a href="{% url 'user:login' %}" class="btn btn-outline-success mt-3">GIRIS YAPALIM</a>
            </div>
        </div>
        <br><br><br>
        {% include 'footer.html' %}
    </div>
{% endblock %}

templates/kapilar.html
{% extends 'base.html' %}
{% load static %}

<title>{% block title %}KAPI TIPLERI{% endblock %}</title>

{% block body %}
    <div class="container-fluid mt-3">
        <div class="bg-success">
            <img src="{% static 'img/metaxdoor-doner-kapı-revolving-door.jpg' %}" alt="imalat resmi"
                 style="max-height: 7rem;"/>
        </div>
        <div class="services-area section-gap">
            <div class="container">
                {% if request.user.is_authenticated %}
                    <div class="row">
                        <div class="col-md-12 mt-2">
                            <p class="text-danger, bg-success">
                            <h4>Kapı Tipleri</h4>
                            <hr>
                        </div>
                    </div>

                    <div class="container">
                        <div class="row row-cols-2 row-cols-lg-6 g-2 g-lg-2">
                            <div class="col">
                                <div class="p-3 border bg-white" style="width: 13rem;">
                                    <a href="{% url 'home:aboutsld' %}">
                                        <img src="{% static 'img/sld.jpg' %}" class="card-img-top" style="height: 9rem;"
                                             alt="Kayar kapi">
                                    </a>
                                    <div class="card-body">
                                        <a href="{% url 'home:aboutsld' %}"><h4 class="text-success">
                                            <strong>SLD</strong></h4>
                                        </a>
                                        <p class="card-text">Farkli Kayar kapi tiplerinin bulundugu imalat
                                            girisidir.</p>
                                        <a href="{% url 'home:aboutsld' %}" class="btn btn-outline-success">SLD giris
                                            yap</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-3 border bg-white" style="width: 13rem;">
                                    <a href="{% url 'home:aboutmr30' %}">
                                        <img src="{% static 'img/mr30.jpg' %}" class="card-img-top"
                                             style="height: 9rem;"
                                             alt="Kayar kapi">
                                    </a>
                                    <div class="card-body">
                                        <a href="{% url 'home:aboutmr30' %}"><h4 class="text-success">
                                            <strong>MR30</strong></h4>
                                        </a>
                                        <p class="card-text">Farkli Doner kapi tiplerinin bulundugu imalat
                                            girisidir.</p>
                                        <a href="{% url 'home:aboutmr30' %}" class="btn btn-outline-success">MR30 giris
                                            yap</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                {% endif %}
            </div>
            {% include 'footer.html' %}
        </div>
    </div>
{% endblock %}

templates/loginform.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}


<title>{% block title %}GIRIS SAYFASI{% endblock %}</title>
{#<body>#}
{#{% block body %}#}
{#    <div class="container mt-3">#}
{#        <div class="row">#}
{#            <div class="col-sm-4">#}
{#                <div class="card">#}
{#                    <div class="card-header">#}
{#                        <h5>{{ title }}</h5>#}
{#                    </div>#}
{#                    <div class="card-body">#}
{#                        <form method="post" enctype="multipart/form-data">#}
{#                            {% csrf_token %}#}
{#                            {{ form|crispy }}#}
{#                            {{ form.media }}#}
{#                            <br>#}
{#                            <button type="submit" class="btn btn-outline-primary">{{ title }}</button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        <br><br>#}
{#        {% include 'footer.html' %}#}
{#    </div>#}
{#{% endblock %}#}
{#</body>#}


{% block body %}
    <div class="container-fluid mt-3">
        <div class="bg-success">
            <img src="{% static 'img/metaxdoor-doner-kapı-revolving-door.jpg' %}" alt="imalat resmi"
                 style="max-height: 7rem;"/>
        </div>
        <div class="card border-success mt-4 rounded mx-auto d-block" style="max-width: 19rem;">
            <div class="card-header"><h5>Kullanici Girisi</h5></div>
            <div class="card-body text-success">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    {{ form.media }}
                    <br>
                    <button type="submit" class="btn btn-outline-success">{{ title }}</button>
                </form>
            </div>
        </div>
        <br><br>
        {% include 'footer.html' %}
    </div>
{% endblock %}

templates/navbar.html
{% extends 'base.html' %}

{% block body %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light mt-3">
        <div class="container-fluid">
            <a class="navbar-brand mb-0 h1" href="{% url 'home:kapilar' %}">KAPI TIPLERI</a>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </nav>
{% endblock %}